### ISSUE TITLE
Broken cookie behaviour with an existing session.

### ISSUE THREAD

**Issue by SonnyRR** [SoftUni/csharp-web#8]
Added pull request: https://github.com/SoftUni/csharp-web/pull/9

As of commit #https://github.com/SoftUni/csharp-web/commit/3fb04b0887ca23e15c97e72a02cbabe204c1459e the server does not correctly check and manage existing sessions and when to set cookies. When a session is present in the repository-like class the SetResponseSession() always attaches a new cookie with the existing GUID as ID, but with a new date (current UTC local time of the machine) to the response headers.

This should not be the expected behaviour as there is no point to always have Set-Cookie headers in the responses when a session is already present. In the current state it always returns the Set-Cookie header with every response and modifies the expiration dates to basically last the current time of when the request is processed to + 3 days.
https://github.com/SoftUni/csharp-web/blob/3fb04b0887ca23e15c97e72a02cbabe204c1459e/2019-May-Season/SoftUni-Information-Services/src/SIS.WebServer/ConnectionHandler.cs#L94-L102

Here it checks for an existing session and if it's not present we add it to the repository, which prevents us from checking in the SetResponseSession() if we need to add a new session and cookie. IMO this is not the correct behaviour.
https://github.com/SoftUni/csharp-web/blob/3fb04b0887ca23e15c97e72a02cbabe204c1459e/2019-May-Season/SoftUni-Information-Services/src/SIS.WebServer/ConnectionHandler.cs#L76-L92

**Comment by DCay** [comment]
Fixed with #9
